# SPDX-FileCopyrightText: 2022 Digital Dasein <https://digitaldasein.org/>
# SPDX-FileCopyrightText: 2022 Senne Van Baelen <senne@digitaldasein.org>
# SPDX-FileCopyrightText: 2022 Gerben Peeters <gerben@digitaldasein.org>
#
# SPDX-License-Identifier: MIT

FROM ubuntu:20.04

# LABEL about the custom image
LABEL maintainer="senne@digitaldasein.org"
LABEL version="0.1"
LABEL description="Test compono binary on clean Ubuntu 20.04 image."

COPY target/x86_64-unknown-linux-gnu/release/compono /usr/local/bin/compono
