[
("MathJax_Size3-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Size3-Regular.woff"#)),
("MathJax_AMS-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_AMS-Regular.woff"#)),
("MathJax_Fraktur-Bold.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Fraktur-Bold.woff"#)),
("MathJax_SansSerif-Italic.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_SansSerif-Italic.woff"#)),
("MathJax_Vector-Bold.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Vector-Bold.woff"#)),
("MathJax_Calligraphic-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Regular.woff"#)),
("MathJax_Math-Italic.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Math-Italic.woff"#)),
("MathJax_Zero.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Zero.woff"#)),
("MathJax_Vector-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Vector-Regular.woff"#)),
("MathJax_SansSerif-Bold.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_SansSerif-Bold.woff"#)),
("MathJax_Size2-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Size2-Regular.woff"#)),
("MathJax_Script-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Script-Regular.woff"#)),
("MathJax_Main-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff"#)),
("MathJax_Math-BoldItalic.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Math-BoldItalic.woff"#)),
("MathJax_Main-Italic.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Main-Italic.woff"#)),
("MathJax_Size4-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Size4-Regular.woff"#)),
("MathJax_Main-Bold.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Main-Bold.woff"#)),
("MathJax_Typewriter-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Typewriter-Regular.woff"#)),
("MathJax_Fraktur-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Fraktur-Regular.woff"#)),
("MathJax_Size1-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Size1-Regular.woff"#)),
("MathJax_Math-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Math-Regular.woff"#)),
("MathJax_Calligraphic-Bold.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_Calligraphic-Bold.woff"#)),
("MathJax_SansSerif-Regular.woff", include_bytes!(r#"../lib/mathjax/node_modules/mathjax/es5/output/chtml/fonts/woff-v2/MathJax_SansSerif-Regular.woff"#)),
]
